// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpsCore.Data.Context;

#nullable disable

namespace OpsCore.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609072554_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("OpsCore.Core.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ActivityLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Added to inventory",
                            AssetId = 1,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 54, 341, DateTimeKind.Local).AddTicks(3919),
                            EmployeeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Action = "Assigned to employee",
                            AssetId = 2,
                            CreatedAt = new DateTime(2026, 6, 6, 9, 25, 54, 343, DateTimeKind.Local).AddTicks(2941),
                            EmployeeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Action = "Status updated to Maintenance",
                            AssetId = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 9, 25, 54, 343, DateTimeKind.Local).AddTicks(2960),
                            EmployeeId = 1
                        });
                });

            modelBuilder.Entity("OpsCore.Core.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastMaintenanceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaintenanceIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeId = 1,
                            EmployeeId = 1,
                            LastMaintenanceDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Office A-101",
                            MaintenanceIntervalDays = 90,
                            Name = "Dell Latitude 5520",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeId = 1,
                            EmployeeId = 2,
                            LastMaintenanceDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Office B-202",
                            MaintenanceIntervalDays = 180,
                            Name = "MacBook Pro 16",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeId = 2,
                            LastMaintenanceDate = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Server Room",
                            MaintenanceIntervalDays = 60,
                            Name = "Dell PowerEdge R740",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            AssetTypeId = 4,
                            LastMaintenanceDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Server Room",
                            MaintenanceIntervalDays = 120,
                            Name = "Cisco Switch 48 Port",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            AssetTypeId = 5,
                            LastMaintenanceDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Office A-101",
                            MaintenanceIntervalDays = 90,
                            Name = "HP LaserJet Pro",
                            Status = 0
                        });
                });

            modelBuilder.Entity("OpsCore.Core.Models.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Server"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Router"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Switch"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Printer"
                        });
                });

            modelBuilder.Entity("OpsCore.Core.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("OpsCore.Core.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnDuty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "john@opscore.com",
                            FirstName = "John",
                            IsOnDuty = true,
                            IsPresent = true,
                            LastName = "Smith",
                            Password = "",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "sarah@opscore.com",
                            FirstName = "Sarah",
                            IsOnDuty = true,
                            IsPresent = false,
                            LastName = "Chen",
                            Password = "",
                            PhoneNumber = "0123456788"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "mike@opscore.com",
                            FirstName = "Mike",
                            IsOnDuty = false,
                            IsPresent = false,
                            LastName = "Johnson",
                            Password = "",
                            PhoneNumber = "0123456787"
                        });
                });

            modelBuilder.Entity("OpsCore.Core.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("PerformedById");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("OpsCore.Core.Models.ActivityLog", b =>
                {
                    b.HasOne("OpsCore.Core.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpsCore.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OpsCore.Core.Models.Asset", b =>
                {
                    b.HasOne("OpsCore.Core.Models.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpsCore.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("AssetType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OpsCore.Core.Models.Employee", b =>
                {
                    b.HasOne("OpsCore.Core.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OpsCore.Core.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("OpsCore.Core.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpsCore.Core.Models.Employee", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("PerformedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
